# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

menu:
- {name: 'אודות', path: 'menu', url: 'about.html'}
- {name: 'כתיבה', path: 'menu', url: 'writing.html'}
- {name: 'צרו קשר', path: 'menu', url: 'contact.html'}


# Customize site text
pagination:
  next_page: 'הבא'
  previous_page: 'הקודם'

# sharing_button_prompt: 'מוזמנים לשתף'

related_posts: 'פוסטים קשורים:'

post_date_prefix: 'נכתב בתאריך'
